[book]
authors = ["Alisue"]
language = "en"
multilingual = false
src = "src"
title = "Iterate Website Development"

[preprocessor.alerts]

[preprocessor.mermaid]
command = "mdbook-mermaid"


[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
